name: "Podcast Generator"
author: "Solenoid"
description: "Generates a podcast episode based on a given topic."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: 'Red'
  icon: "git-branch"
inputs:
  email:
    description: "Commiter's email address."
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Commiter's name."
    required: true
    default: ${{ github.actor }}
